### ISSUE TITLE
Add Zoom Call Lectures and Exam dates of 044102 to Calendar

### ISSUE THREAD

**Issue by PNone** [michael-maltsev/technion-ug-info-fetcher#2]
The course 044102 has a single lecture that occurs on 2 dates and 1 exam with 2 chances to take it.
However, this program parses the data in a way that puts the lecture days in הערות
and the exam dates as
"בוחן מועד א":"07-03-2024","בוחן מועד ב":"18-03-2024"
instead of
"מועד א":"07-03-2024","מועד ב":"18-03-2024"

May you please fix the parsing for this course (and similar ones)?
If lecture dates can't be fixed, can the exam dates be fixed so they could appear on cheesefork properly?

**Comment by michael-maltsev** [comment]
The goal of the technion-ug-info-fetcher project is to export information from [the Technion students portal](https://students.technion.ac.il/local/technionsearch/search) to an accessible format, such as JSON, in a way that resembles the original information as closely as possible. It seems to be doing it correctly for the 044102 course as well. The real problem here is that the students portal does a poor job of presenting the information.

> this program parses the data in a way that puts the lecture days in הערות

> and the exam dates as [...]

You can see in the following screenshot that that's exactly how the information is presented [on the students portal page](https://students.technion.ac.il/local/technionsearch/course/44102):

![image](https://github.com/michael-maltsev/technion-ug-info-fetcher/assets/36999014/2efc2d3d-f5b1-468f-afb1-c4668ce8fd81)

The best solution for that is to contact the course staff and ask them to improve the way the information is presented on the students portal page.

In any case, addressing this is out of scope for technion-ug-info-fetcher, so I'm closing this issue. I saw that you opened an issue about this in CheeseFork as well (https://github.com/michael-maltsev/cheese-fork/issues/34). Addressing it in CheeseFork might work, we'll continue the discussion there.
